name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  trigger_webhook:
      runs-on: ubuntu-latest
      steps:
        - name: Trigger Webhook
          run: |
            PAYLOAD=$(echo -n '{"ref": "refs/heads/dev", "event_name": "push", "branch": "dev", "target": "/srv/www/default/graphit-test" }')
            curl -X POST \
                -H "Content-Type: application/json" \
                -H "X-Hub-Signature: sha1=$(echo -n $PAYLOAD | openssl dgst -sha1 -hmac ${{ secrets.WEBHOOK_SECRET }} | awk '{print $2}')" \
                -d "$PAYLOAD" \
                ${{ secrets.WEBHOOK_URL }}
          env:
            PAYLOAD: '{"ref": "refs/heads/dev", "event_name": "push"}'

